apiVersion: v1
kind: Service
metadata:
  name: blog-website-frontend
spec:
  type: NodePort
  selector:
    app: blog-website-frontend
  ports:
    - port: 4200
      targetPort: 4200
      nodePort: 30012
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-website-frontend
  labels:
    app: blog-website-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-website-frontend
  template:
    metadata:
      labels:
        app: blog-website-frontend
    spec:
      containers:
        - name: flutter-web
          image: rihabbennour/blog-website-frontend:latest
          ports:
            - containerPort: 4200
